### ISSUE TITLE
D2DX edition can't show the Project Diablo 2's quick cast icons

### ISSUE THREAD

**Issue by weili0677** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#116]
In the Project Diablo 2 Mod(www.projectdiablo2.com)  Singleplayer mode with the newest D2DX and enter game that can't see the PD2's  
 "quick cast" icons.If set BuildinResMod to false them can show normally.
so may be It is "tile culling" stuff? Can you fix it?please.

**Comment by weili0677** [comment]
I fix it by myself. Thank you.

**Comment by IAmTrial** [comment]
Maybe this can serve as an example to future reporters of how NOT to report and close an issue.

D2DX from bolrog's repository is outdated by years, any bugs that were in that version's SGD2FreeRes may have already been fixed. Always use the modern release from this repo.

D2DX is known to have various graphical problems. Do other Glide wrappers have the same problem?

The problem is related to a custom feature that is implemented by a 3rd party and is not related to resolution changing. I cannot support custom features that are implemented by other mods unless that mod team requests my help. My responsibility is to make sure that the resolution mod can change your game resolution, and all vanilla entries appear where they should.

The issue was closed, with a useless "I fixed it! Thanks." How did you fix it, so that the next person with the same exact issue has an answer for the problem? I need to know how this issue was resolved, in case this actually turns out to be a bug.

The next time a bug reporter resolves a bug without further comment on how it was resolved, I will be blocking them from this repo.
