### ISSUE TITLE
with basemod, cann't use posion with right click when slash opened

### ISSUE THREAD

**Issue by wu-kang66** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#132]
sometimes, no response,  sometimes crash.
https://drive.google.com/file/d/12_8PKWZtaj8Gda2_pbWHdjQcKOQui6fm/view?usp=sharing

**Comment by IAmTrial** [comment]
What version are you running, and are you running the game with clean files, or are there other mods that you are running at the same time?

**Comment by wu-kang66** [comment]
game version 1.13c or 1.14d have the same problem, and I use the origin game just with plugy and basemod.

**Comment by IAmTrial** [comment]
Tested with only SGD2FreeRes, it works. Tested against PlugY, it works. Tested against Basemod and SGD2FreeRes without PlugY, doesn't work. This happens in any resolution mode.

This is a bug associated with Basemod and not SGD2FreeRes. Please report the bug to them.

**Comment by wu-kang66** [comment]
Hi, @IAmTrial I have posted the bug to Basemod author also, but he also think it is not a bug of basemod. Do you know him？
May you connect him and solve the bug with him？ These two mods are also good, I sincecely hope they can work togethor well.
![image](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/assets/157418566/4ab538d2-e1c3-4001-b54a-ecee90a51381)

**Comment by IAmTrial** [comment]
Here is why I closed your issue:

1. I don't have the source code to Basemod, so I can only guess which of my own patches conflicts with Basemod. Meanwhile, my source code is open source, so the Basemod developer will have a much easier time fixing the issue from their side, or filling a pull request to fix this problem between our projects.
2. If the Basemod author modified belt.txt or inventory.txt, then the values for 800x600 entries need to be 100% correct for SGD2FreeRes to calculate their new positions in other resolutions. I am not going to audit any of Basemod's TXT files, and I am also going to assume that the file names are also obfuscated.
3. This bug only happens with Basemod combined with SGD2FreeRes. No other mod combination that I am aware of produces this unique interaction.
4. The need to use the belt while the stash is open is such an extremely uncommon occurrence. The vanilla game doesn't even let you press the keyboard hotkeys to consume items from the belt. Combine this with point 3, this issue is of very low priority.

**Comment by wu-kang66** [comment]
@IAmTrial Thank you for reply so seriously. I know.
