### ISSUE TITLE
d2loader :Could not determine the game version from the file signature.

### ISSUE THREAD

**Issue by tlerbao** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#139]
![CleanShot 2024-09-06 at 17 15 00@2x](https://github.com/user-attachments/assets/96d834a6-ffd8-4674-a25b-cb40f9e983df)

Does it support d2loader operation?

**Comment by IAmTrial** [comment]
If D2Loader is an executable replacement for Diablo II, then it will be not work until I implement compatibility for this program.

**Comment by tlerbao** [comment]
If D2Loader is an executable replacement for Diablo II, then it will not work until I implement compatibility for this program.

So, do you have time to develop a version compatible with D2Loader?

**Comment by IAmTrial** [comment]
> If D2Loader is an executable replacement for Diablo II, then it will not work until I implement compatibility for this program.
> 
> So, do you have time to develop a version compatible with D2Loader?

I'll need you to provide a link to D2Loader, in order to confirm what program you are referencing. After that, then I can estimate how long it may take to implement support.

**Comment by tlerbao** [comment]
[D2Loader.exe.zip](https://github.com/user-attachments/files/17973511/D2Loader.exe.zip)

**Comment by IAmTrial** [comment]
Thanks for the download link.

I've taken a quick look at this file, but I need more information to help me understand what this program does. Based on my own research, this appears to be a program developed by Onlyer, and is used to change CD keys, enable multiclient, and load hacks. The only mentions of this tool are on forum posts related to botting. I'm not in favor of supporting a client that is specifically designed for botting.

Could you provide links that explain what this program does?

**Comment by Jarcho** [comment]
You can get the game version from calling into bnclient.dll rather than from game.exe. This is how the game gets it when printing it on the title screen. There's also a third build number in there that isn't printed.

I can get that to you once I finishing setting up my new computer. All my notes are currently on drives not hooked up to anything right now.

**Comment by IAmTrial** [comment]
@Jarcho 

If I recall, that would be using BnClient.dll's QueryInterface.

After calling that function, call the functions at the returned address plus offset 0x5C (patch number) in 1.06 and above. 1.05b and below place the function at 0x58. 1.10 and above (not 1.10 beta or 1.10s beta) allows calling another function at offset 0xB0 (build number).

1.14 still requires checking Game.exe, because of the monolithic executable.

Given the lack of consistency across versions, they aren't exactly the best choice to rely on, but they can be used as a secondary check as in addition to using Game.exe. Note that the version detection mechanism seeks to be compatible with all versions of the game.

We might want to move this conversation to a different discussion, since I've discovered some other reasons why D2Loader might not be working.

**Comment by IAmTrial** [comment]
@tlerbao What version of the game are you encountering this error?

**Comment by tlerbao** [comment]
> @tlerbao What version of the game are you encountering this error?

1.13c

**Comment by IAmTrial** [comment]
After some further review, and a lack of convincing information online, I've decided that I will not support D2Loader. Every single feature that it provides is already implemented elsewhere.

- No-CD: Use GalaxyHaxz's verifiably **clean** no-cd uploads. 1.12 and above do not need the CD to play.
- Key swapping: Keys are mostly relevant for installing and for use on BNet. SGD2FreeRes is specifically hardcoded to not work on BNet.
- Multiclient: A one byte patch to D2GFX.dll that has information online. Can be done with a simple hex editor.
- Map reveal / QoL: Use the packages provided by your server.

Some distributions of D2Loader are designed to steal your D2 keys, which is yet another reason why I do not want to support it. There are much safer alternatives available that don't carry such a risk to your system (and my system as well).

**Comment by tlerbao** [comment]
@IAmTrial d2load It's not just the no-cd function, there are many commands that support various features, and it also supports scripts, allowing for even more functionality through the D2hack.script file.
For example, write in D2hack.script D2Game.dll 0X152E8 BAC590C66AF7E2 BA06000000EB13 1
##Force bright gold weapons, armor, rings, and necklaces to have exactly 6 affixes.
