### ISSUE TITLE
What are the build instructions~~

### ISSUE THREAD

**Issue by MxCen** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#2]
Hi, I attempted to build the source on Windows10 with the following:

I wanted to check if I'm following the right steps before starting triage on the build errors.

**Comment by IAmTrial** [comment]
I don't know how I managed to not see this for almost a month, but I should respond. This project is quite complicated to get working, but I will try to explain.

First, the code is currently meant to compile with VS 2019, due to its heavy usage of C++20. You will need to create a new project, and add the files into the project. To simplify things, you can use the "Show All Files" button in the solution explorer. The project will need to output a DLL file, and should be set to compile for the latest C++ standard draft.

Second, the project is dependent on external libraries. You need to add the include directories into the project.  The library directories also needs to be added, and related LIB files need to be linked to. Those libraries are:
- [fmtlib](https://github.com/fmtlib/fmt), build it after setting it up with CMAKE
- [SGD2MAPI (C++)](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-API), you will want to compile it as a LIB file, as DLL file is more complicated but ask me if you want to do that
- [rapidjson](https://github.com/Tencent/rapidjson), header only include file
- [mjsoni](https://github.com/IAmTrial/Multi-JSON-Interface), header only include file

Third, is a step required to compile SGD2MAPI (C++). You need to run the Python script in the C++ folder from [D2 Address Table](https://github.com/mir-diablo-ii-tools/Diablo-II-Address-Table), which will automatically embed all of the address definitions into a source file.  Place the resulting CC file into the SGD2MAPI project at "src\cxx\backend".

Finally, as a matter of licensing, if you intend on distributing the resulting binary (e.g. DLL file), then you agree that any changes you make must conform to AGPLv3 and that the file shall accompany the LICENSE and COPYING files in the same distributed package.  You cannot statically link to MSVC's libraries (e.g. "Multi-threaded", "Multi-threaded Debug"), but you may dynamically link to them (e.g. "Multi-threaded **DLL**", "Multi-threaded Debug **DLL**").

Let me know if this is making any sense at all. Yes, I know I should've used CMAKE or similar, but I'mm too dumb to figure it out.

**Comment by IAmTrial** [comment]
So I've returned to this relatively old issue to present an update. I am in the process of adding CMake support to this project, so that other users can more easily modify this project (plus lessen the setup time on my side after a `git clone`). I will also be adding a Visual C++ 6.0 workspace and project file alongside the `CMakeLists.txt` file primarily for those that want to compile a binary that I would use for releases.

**Comment by IAmTrial** [comment]
The `master` branch, which is used for the current releases, is now able to be set up using CMake.

The `develop` branch is still broken for now.

If there is no further discussion on this within a week, I will close this issue.
