### ISSUE TITLE
for patch 1.14d

### ISSUE THREAD

**Issue by iamyoyz** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#3]
hi can i ask if this one works for 1.14d?

**Comment by IAmTrial** [comment]
This currently does not work with 1.14D, at the moment it only works with 1.09D.

**Comment by iamyoyz** [comment]
I hope you could in the future 😁

**Comment by IAmTrial** [comment]
It is possible to port to 1.14D, but I would want to get some other priorities worked out before I get into 1.14D.

**Comment by iamyoyz** [comment]
its ok if you need a tester I would happy to help 😎

**Comment by IAmTrial** [comment]
I will likely be doing a port to 1.13D, and then to 1.14C.

**Comment by tytannial** [comment]
For 1.14d, it looks good.
https://github.com/shalzuth/D2Launcher

**Comment by IAmTrial** [comment]
Functionally, the code pretty much works for the versions I plan on supporting. The only thing that stops me from putting this onto 1.14D is locating all the patch locations. The reason why I want to start with 1.14C is because the code in that version bears more resemblance to 1.13D. This means that I can spend less time on making a port to another version. The version 1.14D could be very likely the same, but there are some quirks that would have me writing more code just in case.

Is there anything that makes 1.14D more lucrative to use compared to 1.14C?

**Comment by tytannial** [comment]
For research, I think it should be step by step. 🙄

**Comment by IAmTrial** [comment]
All I ask for is patience. Then you will have it.

**Comment by iamyoyz** [comment]
thanks for giving us hope 😁

**Comment by IAmTrial** [comment]
Patch 1.14C support should be coming soon. If you want are willing to settle for a 1.14C port, then I will create a release. Otherwise, I will start with the 1.14D port and I will create a release once that is completed.

**Comment by iamyoyz** [comment]
thanks for the update :D I'll just wait patiently for 1.14d but you could
release the 1.14c for others

**Comment by IAmTrial** [comment]
1.14D is now supported for the next release. You will still need to find a way to load SGD2FreeRes.dll into the game.

**Comment by IAmTrial** [comment]
The newest release, 3.0.2.0 contains the changes.

**Comment by iamyoyz** [comment]
thanks so much for this
