### ISSUE TITLE
Is it possible to add "automatic mouse sensitivity scaling" ?

### ISSUE THREAD

**Issue by macrohard** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#30]
When the screen ratio is no longer 4:3, such as 960x600, 1280x720, the mouse movement is a bit erratic. 
cnc-ddraw handles better with this feature.

**Comment by IAmTrial** [comment]
I am not quite sure what kind of behavior you are referring to that is erratic. Could you provide a video or screenshot that displays the exact problem you are facing?

**Comment by macrohard** [comment]
This is a feeling that cannot be explained by video or screenshots.
Specifically, there is a difference in the horizontal and vertical ratio of the cursor movement. Compared with the 4:3 screen ratio, under the 16:10 or 16:9 screen ratio, it feels that the horizontal movement speed of the cursor is faster than the vertical movement speed, resulting in a poorer feel.
If it is convenient, you can use Cnc-ddraw and turn on or off the adjmouse option to find the difference.

**Comment by IAmTrial** [comment]
Using your instructions, I've tested your particular issue. It seems that the issue you are describing has to do with the mouse position scaling that can be affected by resolution. This particular issue is noticeable if running the game in upscaled fullscreen, or in windowed mode with the window maximized.

This is caused by the game simply taking the Windows mouse position (within the game window) and blindly setting the ingame mouse position to that. This means that the mouse will appear to move fast when the resolution is small, and slower when the resolution is larger. In other words, a larger resolution means that the mouse has to move more in order to reach from the left side to the right side, and the top side to the bottom side.  Normally, Diablo II hides the Windows mouse cursor, but if both the Diablo II mouse cursor and the Windows mouse cursor were both visible, you will notice that the Windows mouse is always moving to the upper left side of the Diablo II mouse cursor.

If you are using CnC-DDraw, you can test this by changing `adjmouse`, moving the Diablo II mouse cursor to the bottom right part of the display, and then ALT+TAB to gain visibility of the Windows mouse cursor.

The reason why CnC-DDraw's `adjmouse=true` appears to fix this problem is because the mouse position values are scaled to match the game window. So if both the Diablo II mouse cursor and the Windows mouse cursor were both visible, their positions would mostly match up.

**Comment by macrohard** [comment]
OK, I understand, thank you for your explanation. Currently using your plug-in with CnC-DDraw, it feels good. The only regret is that it cannot be used with Glide Wrapper, which currently does not support the mouse movement scaling function.

**Comment by bolrog** [comment]
@macrohard you could try my alternative wrapper: http://github.com/bolrog/d2dx
