### ISSUE TITLE
Automap position is offset at high resolution. 

### ISSUE THREAD

**Issue by johnsharping** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#31]
First of all, thank you for your wonderful work.
There is a problem, the automap position is offset at high resolution, can it be fixed automatically?Is there an API?
The D2HackMap has two configuration items AutoMapPosX and AutoMapPosY to set offsets, but only supports 720p and 1080p, not all resolutions, such as 1068x600.

**Comment by IAmTrial** [comment]
I am aware that there is an automap misalignment issue that becomes noticeable at relatively high resolutions. However, the issue appears to be a relatively minor issue that I have not specifically prioritized it.

There is no API or automatic way to fix the automap position, simply because I have not made any direct modifications to the automap code.

**Comment by IAmTrial** [comment]
I have done some research into this issue. Using the automap offset variables, I was able to adjust the position of the automap to align with the center of the screen. What I would need to do for SGD2FreeRes is to adjust the automap base position to match closely with the center of the screen.

For reference, the some useful variables that can be used to find patch locations in 1.13C are:
```
D2Client.dll+0x11C1E8, automap x-offset
D2Client.dll+0x11C1EC, automap y-offset
```

However, a quick test in a vanilla game has ultimately made me decide against fixing this issue. In the screenshot below, the 800x600 automap is not aligned to the center of the screen in its unmoved position. The center of the blue X is positioned to the right of the player's character.
![Screenshot001](https://user-images.githubusercontent.com/26683324/120058346-04060080-bfff-11eb-8150-6967e6530660.jpg)

Since this is vanilla behavior and this bug also does not make the game unplayable, I am changing the label of this issue and will now close this issue.
