### ISSUE TITLE
Crash in 1.09

### ISSUE THREAD

**Issue by bolrog** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#39]
With SGD2FreeRes 3.0.2.0 Vanilla and D2 LoD 1.09, I'm getting this error:

![image](https://user-images.githubusercontent.com/81111887/117863760-69828f00-b294-11eb-8542-37cbd7e210e4.png)

**Comment by IAmTrial** [comment]
Is there a particular set of steps for reproducing this error? I've received a previous report of this bug, but I wasn't able to confirm exact cause of this error.

**Comment by bolrog** [comment]
No, I just launched the game as a low level sorc and this happened.

I load the DLL at the time of the first call to Glide if that helps (at the start of the first intro FMV).

I don't think there is anything special about my 1.09 install either...

I did search around in your repositories but this ordinal doesn't seem to be directly referenced? Or maybe I am searching wrong.

**Comment by IAmTrial** [comment]
I attempted to replicate the error in 1.09D in Glide and was not able to replicate the error.

The ordinal is actually defined in two places, both of which are not in this codebase. The ordinal value is stored in a tab-delimited table at [another repo](https://github.com/mir-diablo-ii-tools/Diablo-II-Address-Table) where it is fed as input into [a program](https://github.com/IAmTrial/Diablo-II-Address-Table-Hardcode-Tool) to produce C code. The C related definitions are defined in [SGD2MAPI](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-API).

Unfortunately, the path is not showing in the error due to some mistakes in my own code. Could you post the full path to your Diablo II 1.09D install? If the path contains any personal information, feel free to white-out the information. Let me know if were any characters in that path that are not part of the 7-bit ASCII specifications or if the path has a length of more than 259 characters (including drive letter).

**Comment by bolrog** [comment]
Strange.

My install is in either 

C:\Games\Diablo II\
or
C:\Games\Diablo II_109\

**Comment by IAmTrial** [comment]
I compared the error screenshot from this issue report to another report I received. I can say that the error text is missing the library path, which should be "D2Win.dll". The address that failed to retrieve was D2Win's "UnloadCelFile".

This is highly unusual, since the path is empty when there are no any situations that would cause this problem. Normally, the accesses to SGD2MAPI game address table are done in a way that prevents manual specification of the path. I have checked all points of access to the D2Win UnloadCelFile entry and have not found anything that would manually enter an empty path.

What this appears to be is a symptom of another problem altogether. I hypothesize that the game has crashed for some other reason.

Some notes related to the error:
The game is unloading the DLLs in the backwards order that the DLLs were loaded. This means that D2Win unloads before SGD2MAPI. Afterwards, SGD2MAPI begin to unload and the DLL attempts cleanup of global variables. Some of those global variables are of type CelFile. In SGD2MAPI, CelFile automatically unloads, but is dependent on a function located in D2Win in order to unload. Since D2Win is already unloaded, the game freaks out and doesn't know what to do. However, that doesn't explain why the path is empty. Perhaps the `std::filesystem::path` destructor was called before the CelFile were able to call its destructor? Maybe I should use `wchar_t*` to force the path to be valid until the DLL is fully unloaded, similar to SGD2MAPI98.

**Comment by bolrog** [comment]
Yeah, global variables especially in DLLs have been a headache every time I've tried to do anything useful with variable lifetimes.

I used to be unable to properly tear down D2DX without crashing horribly (this same issue is seen in e.g. Sven's wrapper), until I started intercepting WM_DESTROY on the game window. Maybe you can do that too?

**Comment by bolrog** [comment]
Did you get anywhere on this one?
