### ISSUE TITLE
Black block below Scroll of Inifuss

### ISSUE THREAD

**Issue by oGkspAz** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#81]
This is also mentioned at https://github.com/bolrog/d2dx/issues/165

I do not use D2DX but I am experiencing the same issue, leading me to believe that it is caused by SGD2FreeRes.
I have not tested it exclusively with freeres running though.
![20220329195659_1](https://user-images.githubusercontent.com/13630539/160988173-a1720a06-633f-45d8-9c26-c3d2c82447e5.jpg)

My full setup is:
Diablo II LoD v1.14
BaseMod v1.13.9_1
PlugY v14.03
D2LootFilter v0.6a

**Comment by IAmTrial** [comment]
The likely cause of this issue is that I've changed the draw ordering of the screen background. Normally, the screen background is drawn after most other panel elements, which can cause certain kinds of visual bugs.

At the same time, when the Scroll of Inifuss screen is drawn, a black rectangle area is also drawn. This is normally covered up by the screen background being drawn after other elements. In this case, I will have to remove whatever code is causing the black rectangle to be drawn.

Function causing the issue: D2Client.dll+7DE00

**Comment by IAmTrial** [comment]
Fix found, NOP bytes in range D2Client.dll (1.13C): [0x7C38D, 0x7C3BA).

I will need to apply a patch for all other versions as well.

**Comment by IAmTrial** [comment]
Screenshot, after the patch is applied
![Screenshot001](https://user-images.githubusercontent.com/26683324/175235385-bfea6cb4-d199-4102-9003-f3240abab1b0.jpg)

How to locate the patch location:
1. Scan using open/close state of the Scroll of Inifuss. Scan 0 if closed, 1 if open.
2. Enable "Find All Access" to the variable(s) that are remaining.
3. One of the code paths follows a series of checks, where on is related to the variable that was scanned. Enter the function associated with the related check.
4. A function call is preceded by a `push 0`. Enter that function.
5. Enter the first function that is called.
6. Find a call to D2GFX\_DrawRectangle. This function call, and all pushes need to be NOP.

**Comment by IAmTrial** [comment]
Release 3.0.2.6 contains the bugfix.
