### ISSUE TITLE
Need higher resolution（1366x768 or 1280x720）

### ISSUE THREAD

**Issue by Fyred** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#83]
1068x600 is too small for modern monitors

1366x768 or 1280x720 should be allowed to use on all the Multiplayer online server

thx

**Comment by IAmTrial** [comment]
Single player, LAN, and Open games have unrestricted resolutions. You can change these resolutions in the config file.

Resolutions on Closed multiplayer are decided by the server administration. Read the section on "Multiplayer Use" in README.md, which explains everything.

**Comment by Fyred** [comment]
> Single player, LAN, and Open games have unrestricted resolutions. You can change these resolutions in the config file.
> 
> Resolutions on Closed multiplayer are decided by the server administration. Read the section on "Multiplayer Use" in README.md, which explains everything.

Players can use higher resolution through other mods. So you can't limit anything

**Comment by Fyred** [comment]
I think, you should use a blacklist for multiplayer, not a white list.

**Comment by IAmTrial** [comment]
> Players can use higher resolution through other mods. So you can't limit anything
You already know where to find a solution, so use that if you want unrestricted resolutions then. And like I said before, you are free to add 1366x768 and 1280x720 to your config file and use that in non-closed multiplayer games. 

I'm fully aware that larger resolutions can be used to gain an unfair advantage in multiplayer games, which is why I am using this current system where the server administration has to ask to get server support.

> I think, you should use a blacklist for multiplayer, not a white list.
No. I am not going to create more work for myself by doing that. I do not want to handle more requests than I would get just  to block servers from using this mod. I also do not want to manage a larger server list where servers that could just change IPs at any moment, so I would have to deal with updating the server table more often. I have no interest in disrupting the gameplay experiences of other servers.

If you want SGD2FreeRes to be allowed on your favorite server, you should let the administration of those servers know.

**Comment by Fyred** [comment]
> > Players can use higher resolution through other mods. So you can't limit anything
> 
> You already know where to find a solution, so use that if you want unrestricted resolutions then. And like I said before, you are free to add 1366x768 and 1280x720 to your config file and use that in non-closed multiplayer games.
> 
> I'm fully aware that larger resolutions can be used to gain an unfair advantage in multiplayer games, which is why I am using this current system where the server administration has to ask to get server support.
> 
> > I think, you should use a blacklist for multiplayer, not a white list.
> 
> No. I am not going to create more work for myself by doing that. I do not want to handle more requests than I would get just to block servers from using this mod. I also do not want to manage a larger server list where servers that could just change IPs at any moment, so I would have to deal with updating the server table more often. I have no interest in disrupting the gameplay experiences of other servers.
> 
> If you want SGD2FreeRes to be allowed on your favorite server, you should let the administration of those servers know.

I got it，thank you for your hard work
